### ISSUE TITLE
the nzb file is incomplete with x missing files

### ISSUE THREAD

**Issue by lebnet** [Tensai75/NZBDonkey#11]
Hello

i have a problem with nzbindex.com, i have the following error "the nzb file is incomplete with 31 missing files" (for example with 1575fa055b8643d0ab39f1f7d9c534d3 search) but when i manually search this name on nzbindex i have 32 results. I just have to click on select all > download selected and it's work.

I try to understand why NZBDonkey skip other 31 files.

do you have any suggestion ?

thank you

**Comment by Tensai75** [comment]
NZBDonkey only catches the first hit/upload in the nzbindex.com/nl search results. This is the intended way it works.
The problem in this case is the fact, that for this upload, each rar/par file was uploaded into a different news group and therefore each file was indexed by nzbindex.com as a individual upload. In order for the nzb indexers like nzbindex.com/nl, binsearch.com, etc. to index a upload correctly, all parts have to be uploaded into the same news group.
So this is actually an error (or if intended, a bad behaviour) by the uploader and not an error by the indexers nor NZBDonkey.

**Comment by reloxx13** [comment]
Hey @Tensai75 ,
i acutally have the same behavious with binsearch and i dont understand why.
if i add the nzb manual it will work fine, but nzbdonkey is telling me its not complete

hWumyzGa7x7QUnRX9XvR

is it the same issue? should the uploader change this?

**Comment by Tensai75** [comment]
The issue with binsearch and this upload in particular is that binsearch does index the par2 files and the split zip files as two individual upload.
If you manually search this header on binsearch you see two results, `[15/23] "hWumyzGa7x7QUnRX9XvR.par2" (1/1)` and `[01/23] "hWumyzGa7x7QUnRX9XvR.7z.001" (1/147)`. The first result only contains the par2 files (files 15-23 of 23) and the second contains the split zip files (files 1-14 of 23). However, NZBDonkey only can pick one file and regardless which one is picked, the NZB file will be considered incomplete because 23 files are expected but only 9 or 14 files are present.

**Comment by reloxx13** [comment]
Okay, thank you very much for your explanation <3
