### ISSUE TITLE
nzbindex.nl help

### ISSUE THREAD

**Issue by twistyxxx** [Tensai75/NZBDonkey#14]
Hi, having an issue with adding and using a search index, e.g. nzbindex.nl
when using the nzbdonkey search, it will find nothing, but when manually using the same search term on the nzbindex.nl website, i get search results. Same is for pre-installed nzbindex.com (guess both are the same) I don't have a clue how to fix it

**Comment by Tensai75** [comment]
nzbindex.com and nzbindex.nl are just different domains for the same search engine and provide the exact same results. And nzbindex.com is already included as a default search enginge into NZBDonkey. So no need to add it manually.

Can you provide an example header for which the NZB file can be found manually on nzbindex.com but will not be fetched by NZBDonkey?

**Comment by twistyxxx** [comment]
LP.Katrin-Tequila-NRX-4K.HDL

**Comment by Tensai75** [comment]
The issue here is the indexing of nzbindex.com. This upload was indexed as beeing two different uploads:

![image](https://user-images.githubusercontent.com/34959627/107181985-36eaa100-69dc-11eb-866b-0e639dc83dff.png)

NZBDonkey always fetches the first result returned from the search engines only. This is a limitation of the program because if several results are returned, NZBDonkey has no means to determin which one is the "correct" one.
In this case, the first result is the jpeg file only. But because the subject implies that there must be 52 files for this upload but only one file is present in the NZB file, NZBDonkey considers this NZB file to be incomplete:

```
2021-02-08T05:59:23.982Z - ERROR: no search engine returned any usable result
2021-02-08T05:59:23.982Z - ERROR: NZBIndex: Error: the nzb file is incomplete with 51 missing files
2021-02-08T05:59:23.980Z - INFO: NZBIndex: checking if nzb file is valid and complete
2021-02-08T05:59:23.885Z - INFO: NZBIndex: trying to download the nzb file
2021-02-08T05:59:23.885Z - INFO: NZBIndex: the nzb file download url is: https://nzbindex.com/download/524279606/
2021-02-08T05:59:23.885Z - INFO: NZBIndex: nzb file found
2021-02-08T05:59:23.884Z - INFO: NZBIndex: the search engine returned a JSON response
2021-02-08T05:59:23.613Z - INFO: NZBIndex: searching for the nzb file
2021-02-08T05:59:23.613Z - INFO: NZBIndex: the search url is: https://nzbindex.com/search/json?sort=agedesc&hidespam=1&q=LP.Katrin-Tequila-NRX-4K.HDL
2021-02-08T05:59:23.613Z - INFO: starting to search for the nzb file on the search engines
2021-02-08T05:59:23.609Z - INFO: found header tag: LP.Katrin-Tequila-NRX-4K.HDL
2021-02-08T05:59:23.609Z - INFO: processing parameters passed from the content script
```

If you like you can deactivate the check for completeness, but then you still would only get the NZB file with the jpeg from NZBDonkey.

But anyway, this is not an error or issue but a known limitation of the programm.

Regards, Tensai

**Comment by Tensai75** [comment]
Well maybe I've found a way to improve the NZBDonkey search results in your special usecase.
But again I have to say, that this upload is named in a way, which confuses the indexers and results in wrongly indexed files.
But anyway.

First deactivate the NZB file completness check:
![image](https://user-images.githubusercontent.com/34959627/107324275-1720af00-6aa8-11eb-826e-4f47b49f9466.png)

Then deactivate the default NZBIndex search engine and add a custom search engine with the following settings:
**Search Engine Name:** `NZBIndex`
**Search URL:** `https://nzbindex.com/search/json?sort=sizedesc&hidespam=1&q=%s`
**Response Type:** `JSON`
**JSON object path:** `results.0.id`
**Download URL:** `https://nzbindex.com/download/%s/`

![image](https://user-images.githubusercontent.com/34959627/107324695-cb223a00-6aa8-11eb-81a9-9b3bd8e8da19.png)

With these settings, NZBDonkey will fetch the NZB file from NZBIndex with the biggest file size and send it to the NZB file target without further checking the NZB file for completness.

This might help to improve the results accuracy in this case but might also decrease it in other cases.

Regards, Tensai

**Comment by twistyxxx** [comment]
Thanks for helping me with this. Tried it on another nzb, but it downloaded the wrong file, so I guess it is not possible to make a reliable workaround. Me is wondering, why these nzb only can be found on nzbindex, but not on other sites like nzbking.
Nevertheless, thanks for your effort!
