### ISSUE TITLE
Add "file" to capture the header

### ISSUE THREAD

**Issue by thibbea** [Tensai75/NZBDonkey#2]
Hello is it possible to add word who is captured as header ? like "file" or "title".

thanks

**Comment by Tensai75** [comment]
I don't understand what you actually are requesting. Can you explain in more detail?

**Comment by thibbea** [comment]
Hello,
Sorry English is not my native language.
I go to a Site for my NZB where the world "Header"  is not always use. Sometimes it's "file" or another word.

Like for example:
Files: hjkfhdui
Password: siopiee


So my question is; Is it possible to add the term "file" to do like it was "header" ?

Thanks

**Comment by Tensai75** [comment]
“Header” is the term which should be used on NZB sites because this is the correct name for it. Analyzing the selected text to correctly extract the information for title, header and password is already complicated enough because there is actually no standard between the different NZB sites on how to present the information. Often even on the same site the information is presented differently by different posters. In order to incorporate your request I will therefore need to check how actually the information is presented on this site you are visiting. Can you provide a link to it?

**Comment by thibbea** [comment]
Thanks for aswering me.

link: https://www.kleverig.eu/showthread.php?t=455074

But i think you have not access to it.

Got something like this:
Poster: The Nameless Poster
Post Date: 2019-02-20
Group: alt.binaries.nzb
File: nbmTBugjKwrQLreS
Pass: AJCWW5SKdQek55jM
Release Date: 2019-02-20

**Comment by Tensai75** [comment]
I will try to update the parsing routine in a next update.

**Comment by thibbea** [comment]
Great news.
Another think, since update, i cant validate with keyboard enter key directly after paste somthing in header. In need to clic with mouse.

Thanks a lot for your great work.

**Comment by Tensai75** [comment]
> Another think, since update, i cant validate with keyboard enter key directly after paste somthing in header. In need to clic with mouse.

Well, this is actually intentional to prevent accidental submission of the form (i.e. without having entered all information, e.g. password). I have never tested this but if it worked with the enter key in the last versions, this was indeed rather a bug than a feature :-)

**Comment by Tensai75** [comment]
### v0.7.1
* Improvement: Added "file" as additional keyword for the header information in the function to analyze the selected text
