### ISSUE TITLE
NZB file download interception ...

### ISSUE THREAD

**Issue by lantura** [Tensai75/NZBDonkey#3]
... don't work for this usenet forum:
https://www.brothers-of-usenet.net
None of the 3 options for "Handling of Form Data" work.
Any hints.
Thanks.

**Comment by Tensai75** [comment]
Yes, I am already aware of this and I am still trying to figure out a way to handle NZB file download interception also on this site. However, as far as I can see they seem to use a referrer check or any other kind of protection to prevent such interception/direct access and due to the security restrictions for browser addons, it will most probably not be possible to overcome this protection.

**Comment by Tensai75** [comment]
### v0.7.1
* "Send Form Data as GET request" is now working with BoU.
