### ISSUE TITLE
Store nzb outside of browsers default download location

### ISSUE THREAD

**Issue by daniela-waranie** [Tensai75/NZBDonkey#7]
In my case i want NZBDonkey to save a nzb file to a samba share (other host, not local), while NZBDonkey is running on my Ubuntu 19.10.

In version 0.7.2 there is a warning that one should only enter relative pathes in "Folder for NZB files". 
So i had to enable "Use save as dialog" and select the folder, when starting to download. 

Would be good if this dialog is initialized with last path used. Or even better, that "Folder for NZB files" supports samba shares or at least absolute pathes to samba mount points.

Pathes similar to this should be allowed for "Folder for NZB files":
`/run/user/1000/gvfs/smb-share:server=mynzbhost.local,share=downloader/nzb`

**Comment by Tensai75** [comment]
This behaviour of NZBDonkey is due to the browsers security restrictions:
Automatic background download of a file is only possible within the browsers default download folder as set in the browser settings. And the download save-as dialog also always starts within the browsers default download folder. As said, these are security restrictions which cannot be overcome by any browser extension.

See also here the description of the "download" method of the web extension API: [https://developer.chrome.com/extensions/downloads#method-download](https://developer.chrome.com/extensions/downloads#method-download) 

> A file path _relative_ to the Downloads directory to contain the downloaded file, possibly containing subdirectories. **Absolute paths, empty paths, and paths containing back-references ".." will cause an error.**

You either have to mount your samba share within the browsers default download folder or you can make a symbolic link in your browsers download folder to your samba share.
