### ISSUE TITLE
NZBLNK generation like/via nzbunity

### ISSUE THREAD

**Issue by DarthHTTP** [Tensai75/NZBDonkey#9]
Hi,
1st, thanks for your work, looks good, looking forward to use it.

I'd like to understand if there are any plans for NZBLNK generation also. 
I do understand the content owners need to place themselves the URIs in this format so NZBDonkey picks them up however in practice adoption is complicated. 
I'd like to point out nzbunity which does injection in html and creates a 1-click download. 
Wouldn't be an idea to, for example, consider adding NZBLNK URI generation via nzbunity ?

**Comment by Tensai75** [comment]
Thanks for your contribution.
However, it looks like you misunderstood the concept of NZBlnk links.
NZB Unity works on sites, where you can anyway directly download a NZB file, e.g. indexer sites (e.g. nzbplanet) or nzb search engines (e.g. binsearch). On these sites it just injects some code to directly send those nzb files to NZBGet or SABnzbd. These are no NZBlnk. NZB Unity does not use NZBlnk in any way nor can it handle them.

The main focus of NZBDonkey are usenet boards, where no direct links to a nzb file are posted but only (real) NZBlnk links or just the header and password information in plain text.

And btw: NZBDonkey works just perfect on these indexer sites and nzb search engines as well because of its nzb download interception function which is in my opinion more sophisticated and works in 99% of the sites even if they require a login.
So I really don't see the need to inject any code into these sites to generate a download link which is there anyway...

**Comment by DarthHTTP** [comment]
thanks for the re, 
maybe i've been misunderstood so here we go again:

i'm on a usenet board where there are various ways of posting in plain text of header, poster, group, password; people put in bold, italic, etc this info;

so in order to use NZBDonkey there, just like in the README, i have to select text and choose "Get NZB File" from Chrome's right-click menu; Because of the hectic way plain text works, it doesn't work;   :) (on top of it, i have no feedback from NZBDonkey to what i am doing, but maybe that's for something for another issue);

What i was trying to suggest is injection of html (which can be a proper NZBlnk) like nzbunity does, for multiple sites, with DOM traversing & finding info needed. A, standardised, 1-click download solution. 
I'm stressing NZBlnk because there are ways of extending this into something more complex.

**Comment by Tensai75** [comment]
OK, maybe I misunderstood you but let me explain how the NZBDonkey works:

As you mentioned: the big problem in usenet boards is the fact that the board members post information in very different ways. Almost every board member has its own template how to present the title, header and password information. That is why the NZBlnk has been invented, because it provides a standardized way to pass the title, header and password information to other programs (like the NZBDonkey). A NZBlnk therefore actually works more like an API than an actual link and if a NZBlnk is provide you can simply click it and NZBDonkey will do its job.

However, still a lot of users do not use the NZBlnk. Therefore NZBDonkey also has the option to parse a selected text to search for the title, header and password information.

So if you select a text and choose "Get NZB File" frome the browser right click menu:
![alt text](https://raw.githubusercontent.com/Tensai75/NZBDonkey/gh-pages/screenshots/NZBDonkey_FF_02.jpg "Screen shot 1")

then an overlay window will appear:
![alt text](https://raw.githubusercontent.com/Tensai75/NZBDonkey/gh-pages/screenshots/NZBDonkey_FF_03.jpg "Screen shot 1")

In this overlay window you will see what information the NZBDonkey was able to find in the selected text. But because of the many different ways the information is provided (as mentioned above), extracting the correct information is very very difficult for a script especially because there are no real standardized patterns the script can search for. This is the reason why the NZBDonkey will not always be able to find all information. And this is also the reason why a user action is required to check if the script has actually extracted the correct information. So if the title, header or password fields are empty or contain a wrong information, the user has the possibility to enter or correct this information manually. To make this as easy as possible also the selected text is shown in the overlay window so the the required information can just be copied from there and pasted into the required field. If finally the title, header and password information in the corresponding fields is correct, you click "Get NZB File" on the overlay window and NZBDonkey will then do its job as if you clicked on a NZBlnk.

So...., if I now understand you correctly, if no NZBlnk is provide, you do not want to have to select the text but you want the script to inject some 1-click button or link which will start the NZBDonkey immediately the same way as if you had clicked a NZBlnk? Is that what you want?

In this case I again have to disappoint you. This would not be very reasonable because such a 1-click link would very often be invalid because of the mentioned difficulties to extract the required information from the web site.
