### ISSUE TITLE
house-of-usenet.com

### ISSUE THREAD

**Issue by wetanni** [Tensai75/NZBDonkey#9]
Hi,
trying to make nzb download working with the site house-of-usenet.com, but whatever form handling  I use I get an invalid nzb error. I saw in the closed issues that you made it work with brothers-of-usenet.net, maybe you may fix it for HoU too?

**Comment by Tensai75** [comment]
Sorry for late response.
Interception on house-of-usenet.com is working perfectly with the standard setting ("Send Form Data as POST request"). I don't see any issue here.

**Comment by iljarogoff** [comment]
Tried again, but still getting invalid nzb. Tried all types of handling with no success.

**Comment by Tensai75** [comment]
> Tried again, but still getting invalid nzb. Tried all types of handling with no success.

I have just tested the NZB file download interception on house-of-usenet.com once again with latest NZBDonkey v0.7.4 and with latest Chrome and Firefox. Interception of the NZB file download is working absolutely prefectly regardless of what is set for "Handling of Form Data" (because there is no Form Data on house-of-usenet.com to be handled for the NZB download interception).

There must be some issue on your end. Try uninstalling NZBDonkey completely and re-install it from the addon store again.

**Comment by iljarogoff** [comment]
no chance. removed, installed new, reset settings. everytime i get this:
![grafik](https://user-images.githubusercontent.com/21023840/95652486-96e63f00-0af1-11eb-8b0b-cdee965a10ea.png)
download interception from nzbking et al work as expected
is there a log or a detailed error description available? where can i find it?

**Comment by Tensai75** [comment]
> is there a log or a detailed error description available? where can i find it?

In Firefox you can open the following URL in a new tab: `about:devtools-toolbox?type=extension&id=%7Bdd77cf0b-b93f-4e9f-8006-b642c02219db%7D`
Here you will then see all NZBDonkey logs as well as javascript error messages related to the NZBDonkey background script. But there probably won't be any specific logs related to this.

**Comment by iljarogoff** [comment]
this log was useful, it was a cookie issue. enabling third-party-cookies did the trick, thx 👍
